// This is an autogenerated file from Firebase Studio.
/**
 * @fileOverview Logic to update the "Anime of the Day" in Firestore.
 * This script is intended to be run by a scheduled task (e.g., a daily cron job via Firebase Cloud Functions).
 */

import { getAnimeOfTheDay } from '@/ai/flows/anime-of-the-day-flow';
import type { AnimeOfTheDayOutput } from '@/ai/flows/anime-of-the-day-flow';
import { db } from '../firebaseConfig'; // Adjust path as necessary
import { doc, setDoc, Timestamp } from 'firebase/firestore';

/**
 * Fetches a new "Anime of the Day" from the AI flow and updates it in Firestore.
 */
export async function updateDailyAnimeInDB(): Promise<void> {
  console.log('Starting daily update for Anime of the Day...');
  try {
    const animeSuggestion = await getAnimeOfTheDay();

    if (!animeSuggestion || !animeSuggestion.title) {
      console.error('Failed to get a valid anime suggestion from the AI flow.');
      return;
    }

    // Add/update the lastUpdated timestamp
    const dataToStore: AnimeOfTheDayOutput & { lastUpdated: Timestamp } = {
      ...animeSuggestion,
      lastUpdated: Timestamp.now(),
    };

    // Reference to the specific document where Anime of the Day is stored
    const animeDocRef = doc(db, 'app_data', 'anime_of_the_day');

    // Set the document with the new anime data
    await setDoc(animeDocRef, dataToStore);

    console.log(`Successfully updated Anime of the Day in Firestore: ${dataToStore.title}`);
  } catch (error) {
    console.error('Error updating Anime of the Day in Firestore:', error);
    // Depending on your setup, you might want to throw the error
    // or handle it in a way that your scheduled task runner can see (e.g., logging to error reporting services)
    // For now, we just log it.
  }
}

// If you want to be able to run this script directly (e.g., for testing, though not recommended for production scheduling)
// you could add something like:
// if (require.main === module) {
//   updateDailyAnimeInDB().then(() => console.log('Manual update complete.')).catch(e => console.error('Manual update failed:', e));
// }
